name: 'karem alsina '
favicon: null
layout_spectrum: 0.73239
typography_spectrum: 0.237
title: karem alsina arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f9ff'
    - '#3874bc'
    - '#90ccfe'
    - '#1d476d'
    - '#0f161c'
  brandStrength: 0.5726913814432919
  lightness: 0.5939808625262231
  saturation: 0.9357807345222682
  rhythmicContrast: 0.5960085080005229
purpose: []
