name: 'karem alsina '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16252
title: karem alsina arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fafe'
    - '#2872b8'
    - '#030304'
    - '#92cffc'
    - '#6c7b51'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
