name: 'karem alsina '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16252
title: karem alsina arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#265a70'
    - '#42829b'
    - '#8ac0b7'
    - '#91deeb'
    - '#ccfdfb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
