title: karem alsina arts
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#265a70'
    - '#42829b'
    - '#8ac0b7'
    - '#91deeb'
    - '#ccfdfb'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'karem alsina '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.16252
layout_spectrum: 0.3978495
